name: Docs

on:
  push:
    branches: [ "main" ]
    paths: [ "docs/**" ]
  pull_request:
    branches: [ "main" ]
    paths: [ "docs/**" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --profile ci --verbose
    - uses: actions/upload-artifact@v4
      with:
        name: cobl-ci
        path: target/ci/cobl

  docs-build:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v4
        with:
          name: cobl-ci
          path: target/ci
      - name: Cobl Permissions
        run: chmod a+x target/ci/cobl
      - name: Docs
        run:  target/ci/cobl run /docs/build
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs/cobble/site
  
  docs-deploy:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    needs: docs-build
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1