name: Release

on:
  release:
    types: [ "created" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  release_windows_exe:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release --verbose
    - name: Package
      run: 7z.exe a -tzip cobble_win.zip cobl.exe
      working-directory: ./target/release
    - name: Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "target/release/cobble_win.zip"
        allowUpdates: true
  release_macos_bin:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --release --verbose
      - name: Package
        run: tar -C target/release -cvzf cobble_macos.tgz cobl
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "target/release/cobble_macos.tgz"
          allowUpdates: true
  release_linux_bin:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --release --verbose
      - name: Package
        run: tar -C target/release -cvzf cobble_linux.tgz cobl
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "target/release/cobble_linux.tgz"
          allowUpdates: true
