name: Release

on:
  release:
    types: [ "created" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  release_windows_exe:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release --verbose
    - name: Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "target/release/cobl.exe"
        allowUpdates: true
  release_macos_bin:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --release --verbose
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "target/release/cobl"
          allowUpdates: true
  release_linux_bin:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --release --verbose
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "target/release/cobl"
          allowUpdates: true
