name: Release

on:
  release:
    types: [ "published" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  release_windows_exe:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --release --verbose
      - name: Package
        run: 7z.exe a -tzip cobble_win.zip cobl.exe
        working-directory: ./target/release
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "target/release/cobble_win.zip"
          allowUpdates: true
          omitBody: true
          prerelease: true
          makeLatest: false

  release_macos_bin:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --release --verbose
      - name: Package
        run: tar -C target/release -cvzf cobble_macos.tgz cobl
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "cobble_macos.tgz"
          allowUpdates: true
          omitBody: true
          prerelease: true
          makeLatest: false

  release_linux_bin:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --release --verbose
      - name: Package
        run: tar -C target/release -cvzf cobble_linux.tgz cobl
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "cobble_linux.tgz"
          allowUpdates: true
          omitBody: true
          prerelease: true
          makeLatest: false

  release_linux_deb:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Install cargo-deb
        run: cargo install cargo-deb
      - name: Package
        run: cargo deb
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "target/debian/*.deb"
          allowUpdates: true
          omitBody: true
          prerelease: true
          makeLatest: false

  publish_release:
    runs-on: ubuntu-latest
    needs:
      - release_windows_exe
      - release_macos_bin
      - release_linux_bin
      - release_linux_deb
    permissions:
      contents: write
    steps:
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          prerelease: false
          omitBody: true
